version: '3.7'
services:
  web:
    container_name: cashback-service
    build: .
    volumes:
      - .:/opt/btc
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cashback